# -*- coding: utf-8 -*-
"""Autism_Chatbot_1_15_1_4_CHECKPOINTFINAL-8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tI5P5TJG4AcIK_w782UlVDH3fFGSnz46
"""

# CELL 1: Install Required Libraries
!pip install -q PyMuPDF sentence-transformers faiss-cpu torch transformers gradio scikit-learn rouge-score nltk
!pip install -q peft bitsandbytes evaluate datasets bert-score
!pip install -q langchain langchain-community langchain-text-splitters
!pip install trl

print("Libraries installed successfully!")

# CELL 2: Import All Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import time
import os
import torch
import fitz  # PyMuPDF
from transformers import (
    T5ForConditionalGeneration, T5Tokenizer, TrainingArguments, Trainer,
    DataCollatorForSeq2Seq
)
from peft import LoraConfig, get_peft_model, TaskType
from sentence_transformers import SentenceTransformer
import faiss
import pickle
import warnings
import json
import datetime
import re
import gc
from tqdm import tqdm
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.model_selection import train_test_split
from datasets import Dataset
import evaluate
from rouge_score import rouge_scorer
from nltk.translate.bleu_score import sentence_bleu, SmoothingFunction
from nltk.tokenize import word_tokenize
import nltk
from pathlib import Path
import shutil
from langchain_text_splitters import RecursiveCharacterTextSplitter

# Download NLTK data
nltk.download('punkt', quiet=True)
nltk.download('punkt_tab', quiet=True)

warnings.filterwarnings('ignore')

print("All libraries imported successfully!")
print(f"PyTorch version: {torch.__version__}")
print(f"GPU Available: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"GPU: {torch.cuda.get_device_name(0)}")
    print(f"Memory: {torch.cuda.get_device_properties(0).total_memory / 1e9:.2f} GB")

# CELL 3: Create Directories
print("Setting up local directories in Colab...")
base_dir = '/content/PDF_ChatBot_Project'
model_dir = f'{base_dir}/models'
results_dir = f'{base_dir}/results'
plots_dir = f'{base_dir}/plots'
training_data_dir = f'{base_dir}/training_data'

for dir_path in [base_dir, model_dir, results_dir, plots_dir, training_data_dir]:
    os.makedirs(dir_path, exist_ok=True)
    print(f"Created/Verified: {dir_path}")

print("Local directories ready!")

# CELL 4 (REVISED): Upload and CLEAN PDF Files
import re
from google.colab import files

print("Please upload your PDF files for training...")
uploaded_files = files.upload()

pdf_documents = []
pdf_names = []

def clean_text(text):
    # 1. Remove specific headers/footers observed in your logs
    # Pattern looks for "Lord et al." and "Page X"
    text = re.sub(r'Lord et al\. Page \d+.*?\n', '', text, flags=re.DOTALL)
    text = re.sub(r'Lancet\. Author manuscript.*?\n', '', text, flags=re.DOTALL)
    text = re.sub(r'Author Manuscript', '', text)

    # 2. Remove URL artifacts
    text = re.sub(r'http\S+', '', text)

    # 3. Fix broken hyphenations (e.g., "treat- ment" -> "treatment")
    text = re.sub(r'(\w+)-\s+(\w+)', r'\1\2', text)

    # 4. Remove multiple spaces/newlines
    text = re.sub(r'\s+', ' ', text).strip()
    return text

for filename in uploaded_files.keys():
    print(f"\nProcessing: {filename}")
    doc = fitz.open(filename)
    text = ""
    for page in doc:
        text += page.get_text()
    doc.close()

    # Apply cleaning
    cleaned_text = clean_text(text)
    pdf_documents.append(cleaned_text)
    pdf_names.append(filename)

    print(f"Original length: {len(text)} -> Cleaned length: {len(cleaned_text)}")

print(f"\nProcessed {len(pdf_documents)} PDFs successfully!")

# CELL 5
# 1. Define the splitter
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=1500,       # Increased from 600 to capture full paragraphs/sections
    chunk_overlap=300,     # Increased to maintain strong context across boundaries
    separators=["\n\n", "\n", ". ", " ", ""]
)

pdf_chunks = []

for i, doc_text in enumerate(pdf_documents):
    # 2. Split the cleaned text
    raw_chunks = text_splitter.split_text(doc_text)

    # 3. Optional: Prepend filename to each chunk for better grounding
    source_name = pdf_names[i]
    for chunk in raw_chunks:
        # This acts as a "breadcrumb" for the AI
        contextualized_chunk = f"Source: {source_name}\nContent: {chunk}"
        pdf_chunks.append(contextualized_chunk)

print(f"Total chunks created: {len(pdf_chunks)}")

# Install LangChain if not already installed
!pip install -q langchain langchain-community

print("LangChain installed successfully!")

# CELL 6: Create FAISS Index and Define Retrieval Function
import faiss
import numpy as np
from sentence_transformers import SentenceTransformer

print("Initializing SentenceTransformer and FAISS index...")

# 1. Initialize the stronger BGE model
embedder = SentenceTransformer('BAAI/bge-small-en-v1.5')

# 2. Embed chunks AND normalize them (Required for Cosine Similarity)
print(f"Embedding {len(pdf_chunks)} chunks... This might take a moment.")
chunk_embeddings = embedder.encode(pdf_chunks, normalize_embeddings=True, convert_to_numpy=True)

# 3. Create an Inner Product FAISS index (This calculates true Cosine Similarity)
dimension = chunk_embeddings.shape[1]
faiss_index = faiss.IndexFlatIP(dimension)
faiss_index.add(chunk_embeddings)
print(f"FAISS index successfully created with {faiss_index.ntotal} vectors.")

# 4. Define the retrieval function WITH the required BGE instruction
def retrieve_top_k_chunks(question, k=3):
    """Retrieve top k relevant chunks for a question"""
    # BGE models REQUIRE this specific prefix for search queries to work properly!
    instruction = "Represent this sentence for searching relevant passages: "
    query_text = instruction + question

    q_emb = embedder.encode([query_text], normalize_embeddings=True, convert_to_numpy=True)
    distances, indices = faiss_index.search(q_emb, k)

    retrieved_chunks = [pdf_chunks[i] for i in indices[0]]
    return " ".join(retrieved_chunks)

# Test the retrieval function
test_question = "What is autism?"
test_context = retrieve_top_k_chunks(test_question, k=2)
print(f"\nTest question: {test_question}")
print(f"Retrieved context preview: {test_context[:200]}...")

# Add after Cell 6
def retrieve_hybrid(query, k=5, alpha=0.5):
    """Hybrid search combining dense and sparse"""
    # Get dense results
    instruction = "Represent this sentence for searching relevant passages: "
    q_emb = embedder.encode([instruction + query], normalize_embeddings=True)
    dense_scores, dense_indices = faiss_index.search(q_emb, k*2)

    # Simple retrieval for now (since BM25 not defined)
    results = []
    for score, idx in zip(dense_scores[0], dense_indices[0]):
        chunk_data = {
            'text': pdf_chunks[int(idx)].replace('Source: ilovepdf_merged (2).pdf\nContent: ', ''),
            'source': 'ilovepdf_merged (2).pdf',
            'page': 1,
            'score': float(score)
        }
        results.append(chunk_data)

    return results[:k]

def retrieve(query, k=5):
    """Simple retrieval"""
    return retrieve_hybrid(query, k)

# CELL 7: Generate HIGH-QUALITY QA Pairs from PDFs
print("Generating HIGH-QUALITY QA pairs from PDFs...")

def generate_high_quality_qa(text, target_count=150):
    """Generate meaningful QA pairs from text"""

    # Attempt to split into meaningful paragraphs using double newlines
    paragraphs = re.split(r'\n\s*\n', text)
    paragraphs = [p.strip() for p in paragraphs if len(p.strip()) > 200]

    # If too few paragraphs are found, try splitting by sentences for more granularity
    if len(paragraphs) < 5 and len(text) > 1000:
        sentences = nltk.sent_tokenize(text)
        # Group sentences into larger chunks to form 'paragraphs'
        paragraphs = [" ".join(sentences[i:i+3]) for i in range(0, len(sentences), 3)
                      if len(" ".join(sentences[i:i+3]).strip()) > 200]
        print("  (Info: Few paragraphs found with double newline; attempting sentence-based grouping.)")

    print(f"Found {len(paragraphs)} paragraphs suitable for QA generation.")

    qa_pairs = []

    # Look for definition patterns
    definition_patterns = [
        r'(.*?) is (?:a|an|the) (.*?)(?:\\.|$)',
        r'(.*?) refers to (.*?)(?:\\.|$)',
        r'(.*?) are (?:a|an|the) (.*?)(?:\\.|$)',
        r'(.*?) means (.*?)(?:\\.|$)',
        r'(.*?) can be defined as (.*?)(?:\\.|$)',
        r'(.*?) known as (.*?)(?:\\.|$)',
        r'(.*?) characterized by (.*?)(?:\\.|$)'
    ]

    symptom_keywords = ['symptom', 'sign', 'feature', 'characteristic', 'manifestation']
    cause_keywords = ['cause', 'factor', 'etiology', 'origin', 'risk factor']
    treatment_keywords = ['treat', 'therap', 'intervention', 'management', 'approach', 'strategy']

    for i, para in enumerate(paragraphs[:target_count]):
        if i % 50 == 0 and i > 0:
            print(f"  Processing paragraph {i}/{min(len(paragraphs), target_count)}...")

        # Try to extract definitions
        for pattern in definition_patterns:
            matches = re.findall(pattern, para, re.IGNORECASE)
            for match in matches:
                term = match[0].strip()
                definition = match[1].strip()
                if len(term.split()) <= 4 and len(definition) > 20:
                    qa_pairs.append({
                        'question': f"What is {term}?",
                        'answer': f"{term} is {definition}.",
                        'context': para
                    })
                    break

        # Create "what are the symptoms/causes/treatments" questions
        if any(keyword in para.lower() for keyword in symptom_keywords):
            first_sent = para.split('.')[0] + '.'
            qa_pairs.append({
                'question': "What are the symptoms?",
                'answer': first_sent,
                'context': para
            })

        if any(keyword in para.lower() for keyword in cause_keywords):
            first_sent = para.split('.')[0] + '.'
            qa_pairs.append({
                'question': "What causes autism?",
                'answer': first_sent,
                'context': para
            })

        if any(keyword in para.lower() for keyword in treatment_keywords):
            first_sent = para.split('.')[0] + '.'
            qa_pairs.append({
                'question': "What treatments are available?",
                'answer': first_sent,
                'context': para
            })

    # Remove duplicates
    unique_pairs = []
    seen_questions = set()
    seen_q_a = set()

    for pair in qa_pairs:
        q_a_key = f"{pair['question']}||{pair['answer'][:50]}"
        if pair['question'] not in seen_questions and q_a_key not in seen_q_a:
            seen_questions.add(pair['question'])
            seen_q_a.add(q_a_key)
            unique_pairs.append(pair)

    print(f"Generated {len(unique_pairs)} high-quality QA pairs")
    return unique_pairs[:target_count]

# Generate high-quality QA pairs
# Process ALL PDFs, not just the first one
all_qa_pairs = []
for doc_text in pdf_documents:
    doc_pairs = generate_high_quality_qa(doc_text, target_count=20)
    all_qa_pairs.extend(doc_pairs)

print(f"\nTotal QA pairs generated across all PDFs: {len(all_qa_pairs)}")

# Display sample
print("\nSample QA pairs:")
for i, pair in enumerate(all_qa_pairs[:3]):
    print(f"\n{i+1}. Question: {pair['question']}")
    print(f"   Answer: {pair['answer'][:100]}...")

# CELL 8: Split Data into Train/Validation Sets
from sklearn.model_selection import train_test_split

train_qa, val_qa = train_test_split(all_qa_pairs, test_size=0.15, random_state=42)

print(f"Training samples: {len(train_qa)}")
print(f"Validation samples: {len(val_qa)}")

# Display a sample QA pair
print("\nSample QA pair:")
print(f"Question: {train_qa[0]['question']}")
print(f"Answer: {train_qa[0]['answer'][:100]}...")

# CELL 9 - Prepare Dataset
print("Preparing dataset for Qwen...")

from transformers import AutoTokenizer
from datasets import Dataset

# Setup Tokenizer
model_name = "Qwen/Qwen2.5-1.5B-Instruct"
tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"

def prepare_dataset_with_labels(qa_pairs, max_length=512):
    """Prepare dataset with proper labels for causal LM training"""
    input_ids = []
    attention_masks = []
    labels = []

    skipped = 0

    for pair in qa_pairs:
        # Format according to Qwen's chat template
        messages = [
            {"role": "system", "content": "You are a helpful AI assistant that answers questions based on the given context."},
            {"role": "user", "content": f"Context: {pair['context']}\nQuestion: {pair['question']}"},
            {"role": "assistant", "content": pair['answer']}
        ]

        # Apply chat template
        prompt = tokenizer.apply_chat_template(
            messages[:-1],  # Exclude assistant response
            tokenize=False,
            add_generation_prompt=True
        )

        full_text = prompt + pair['answer'] + tokenizer.eos_token

        # Tokenize
        tokenized = tokenizer(
            full_text,
            truncation=True,
            max_length=max_length,
            padding='max_length',
            return_tensors=None
        )

        # Create labels: -100 for prompt tokens (ignore in loss), actual token ids for answer
        prompt_tokens = tokenizer(
            prompt,
            truncation=True,
            max_length=max_length,
            return_tensors=None
        )['input_ids']

        labels_seq = [-100] * len(prompt_tokens) + tokenized['input_ids'][len(prompt_tokens):]

        # Ensure lengths match
        if len(labels_seq) < max_length:
            labels_seq.extend([-100] * (max_length - len(labels_seq)))
        labels_seq = labels_seq[:max_length]

        # Verify no negative impact from truncation
        if len(pair['answer']) > 50 and sum(1 for x in labels_seq if x != -100) < 10:
            skipped += 1
            continue

        input_ids.append(tokenized['input_ids'])
        attention_masks.append(tokenized['attention_mask'])
        labels.append(labels_seq)

    if skipped > 0:
        print(f"Skipped {skipped} samples due to truncation issues")

    return Dataset.from_dict({
        'input_ids': input_ids,
        'attention_mask': attention_masks,
        'labels': labels
    })

# Create datasets
train_dataset = prepare_dataset_with_labels(train_qa)
val_dataset = prepare_dataset_with_labels(val_qa)

print(f"Training dataset size: {len(train_dataset)}")
print(f"Validation dataset size: {len(val_dataset)}")

# Verify labels
sample = train_dataset[0]
print(f"\nSample verification:")
print(f"Input length: {len(sample['input_ids'])}")
print(f"Label length: {len(sample['labels'])}")
print(f"Non-ignored tokens in labels: {sum(1 for x in sample['labels'] if x != -100)}")

# CELL 10 - Load Qwen with LoRA
print("Loading Qwen with LoRA...")

import torch
import gc
# --- FIX: We need to import AutoModelForCausalLM here ---
from transformers import AutoModelForCausalLM, BitsAndBytesConfig

# Clear memory
if torch.cuda.is_available():
    torch.cuda.empty_cache()
    gc.collect()

# Use 4-bit quantization for larger models, remove if using 1.5B
use_quantization = False  # Set to True only if using 7B model

if use_quantization and "7B" in model_name:
    quantization_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_compute_dtype=torch.float16,
        bnb_4bit_use_double_quant=True,
        bnb_4bit_quant_type="nf4"
    )
    model = AutoModelForCausalLM.from_pretrained(
        model_name,
        quantization_config=quantization_config,
        device_map="auto",
        trust_remote_code=True
    )
else:
    print("Loading base model in full precision...")
    model = AutoModelForCausalLM.from_pretrained(
        model_name,
        torch_dtype=torch.float16 if torch.cuda.is_available() else torch.float32,
        device_map="auto" if torch.cuda.is_available() else None,
        trust_remote_code=True
    )

# Configure LoRA for Qwen
from peft import LoraConfig, get_peft_model, TaskType

lora_config = LoraConfig(
    task_type=TaskType.CAUSAL_LM,
    r=16,  # LoRA rank
    lora_alpha=32,  # LoRA alpha
    # --- FIX: Included MLP projection layers for better knowledge injection ---
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
    lora_dropout=0.1,
    bias="none"
)

# Apply LoRA
model = get_peft_model(model, lora_config)

print("\nTrainable parameters:")
model.print_trainable_parameters()

if torch.cuda.is_available() and not use_quantization:
    model = model.cuda()

# CELL 11 - Set Up Training Configuration for Qwen
import torch
from transformers import TrainingArguments, Trainer

print("Setting up training configuration for Qwen...")

# Calculate proper training steps
epochs = 5
batch_size = 2
grad_accum = 4
total_steps = (len(train_dataset) // (batch_size * grad_accum)) * epochs

print(f"Total training steps: {total_steps}")

training_args = TrainingArguments(
    output_dir=f"{model_dir}/qwen_lora",
    num_train_epochs=epochs,
    per_device_train_batch_size=batch_size,
    per_device_eval_batch_size=2,
    gradient_accumulation_steps=grad_accum,
    warmup_steps=int(total_steps * 0.1),  # 10% warmup
    learning_rate=2e-4,
    weight_decay=0.01,
    logging_dir=f'{results_dir}/logs/qwen_lora',
    logging_steps=5,  # Log every 5 steps
    eval_strategy="steps",
    eval_steps=max(1, total_steps // 10),  # Evaluate ~10 times
    save_strategy="steps",
    save_steps=max(1, total_steps // 5),  # Save 5 times
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    fp16=torch.cuda.is_available(),
    report_to="none",
    save_total_limit=2,
    lr_scheduler_type="cosine",
    optim="adamw_torch",
    remove_unused_columns=False,
    ddp_find_unused_parameters=False if torch.cuda.device_count() > 1 else None,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
)

print("Training configuration ready!")
print(f"  - Total steps: {total_steps}")
print(f"  - Eval steps: {training_args.eval_steps}")
print(f"  - Save steps: {training_args.save_steps}")

# CELL 12: Train the Model
print("="*60)
print("STARTING QWEN TRAINING")
print("="*60)

# Train the model
trainer.train()

print("="*60)
print("TRAINING COMPLETE")
print("="*60)

# Save the model with Qwen-specific naming
model_save_path = f"{model_dir}/qwen_lora_final"
model.save_pretrained(model_save_path)
tokenizer.save_pretrained(model_save_path)

print(f"Model saved to {model_save_path}")

# Optional: Save training metrics
import json

# Get training metrics if available
if hasattr(trainer, 'state') and hasattr(trainer.state, 'log_history'):
    training_logs = trainer.state.log_history
    with open(f"{results_dir}/qwen_training_logs.json", 'w') as f:
        json.dump(training_logs, f, indent=2)
    print(f"Training logs saved to {results_dir}/qwen_training_logs.json")

# Optional: Plot training loss
try:
    import matplotlib.pyplot as plt

    # Extract loss values from logs
    train_losses = []
    eval_losses = []
    train_steps = []
    eval_steps = []

    for log in trainer.state.log_history:
        if 'loss' in log:
            train_losses.append(log['loss'])
            train_steps.append(log['step'])
        if 'eval_loss' in log:
            eval_losses.append(log['eval_loss'])
            # Safely get step or fall back to sequence length
            eval_steps.append(log.get('step', len(eval_losses)))

    if train_losses or eval_losses:
        plt.figure(figsize=(10, 6))

        if train_losses:
            plt.plot(train_steps, train_losses, label='Training Loss', marker='o')
        if eval_losses:
            plt.plot(eval_steps, eval_losses, label='Validation Loss', marker='s')

        plt.xlabel('Steps')
        plt.ylabel('Loss')
        plt.title('Qwen Training Progress')
        plt.legend()
        plt.grid(True)
        plt.savefig(f"{results_dir}/qwen_training_curve.png")
        plt.show()
        print(f"Training curve saved to {results_dir}/qwen_training_curve.png")
    else:
        print("Warning: No loss data was recorded to plot.")
except Exception as e:
    print(f"Could not plot training curve: {e}")

# CELL 12.1 Training and Validation Graphs
# CELL 12.1: Training and Validation Graphs (Save to Google Drive)
import matplotlib.pyplot as plt
import json
import os
import shutil
from google.colab import drive

print("Plotting Training and Validation Curves...")

# Mount drive if not already mounted
drive.mount('/content/drive')
drive_results_dir = '/content/drive/MyDrive/Qwen_RAG_Results'
os.makedirs(drive_results_dir, exist_ok=True)

try:
    log_path = f"{results_dir}/qwen_training_logs.json"
    if os.path.exists(log_path):
        with open(log_path, 'r') as f:
            training_logs = json.load(f)

        train_losses = []
        eval_losses = []
        train_steps = []
        eval_steps = []

        # Parse logs
        for log in training_logs:
            if 'loss' in log:
                train_losses.append(log['loss'])
                train_steps.append(log['step'])
            if 'eval_loss' in log:
                eval_losses.append(log['eval_loss'])
                eval_steps.append(log.get('step', len(eval_losses)))

        # Generate Graph
        if train_losses or eval_losses:
            plt.figure(figsize=(10, 6))

            if train_losses:
                plt.plot(train_steps, train_losses, label='Training Loss', color='teal', marker='o')
            if eval_losses:
                plt.plot(eval_steps, eval_losses, label='Validation Loss', color='orange', marker='s')

            plt.xlabel('Training Steps')
            plt.ylabel('Loss')
            plt.title('Qwen Training & Validation Progress')
            plt.legend()
            plt.grid(axis='y', linestyle='--', alpha=0.7)

            # Save Locally
            local_path = f"{plots_dir}/qwen_training_curve.png"
            plt.savefig(local_path, bbox_inches='tight')
            plt.show()

            # Submit to Google Drive
            drive_path = f"{drive_results_dir}/qwen_training_curve.png"
            shutil.copy2(local_path, drive_path)
            print(f"✅ Training curve successfully saved to Google Drive: {drive_path}")
    else:
        print("Warning: No training logs found to plot.")

except Exception as e:
    print(f"Could not plot training curve: {e}")

# CELL 13: Define Evaluation Functions
print("Defining evaluation functions...")

import re
from sklearn.metrics.pairwise import cosine_similarity
from sentence_transformers import SentenceTransformer
import torch

# Ensure the evaluation script uses the same upgraded model
semantic_model = SentenceTransformer('BAAI/bge-small-en-v1.5')

# Custom refusal string
REFUSAL_STRING = "I do not understand this question, and the topic you mentioned is not present in the provided PDF corpus."

def ask_qwen(model, tokenizer, question, context=None):
    """Generate answer with strict refusal enforcement"""
    if context is None:
        context = retrieve_top_k_chunks(question, k=5)

    # List of topics that should ALWAYS trigger refusal
    FORBIDDEN_TOPICS = [
        'capital', 'france', 'paris', 'london', 'berlin', 'tokyo', 'beijing',
        'invented', 'inventor', 'discovered', 'created', 'founded',
        'tire', 'tyre', 'wheel', 'car', 'vehicle', 'automobile',
        'recipe', 'cook', 'bake', 'ingredient', 'kitchen',
        'stock', 'price', 'share', 'market', 'dollar', 'euro',
        'population', 'people live', 'how many',
        'president', 'prime minister', 'leader',
        'sport', 'game', 'match', 'super bowl', 'world cup',
        'weather', 'temperature', 'forecast', 'rain', 'sunny'
    ]

    # Check if question contains forbidden topics
    question_lower = question.lower()
    contains_forbidden = any(topic in question_lower for topic in FORBIDDEN_TOPICS)

    # Quick rejection for clearly off-topic questions
    if contains_forbidden and (not context or len(context.strip()) < 100):
        return REFUSAL_STRING

    # Format prompt using chat template
    messages = [
        {"role": "system", "content": f"""You are a STRICT PDF assistant. Your ONLY source of knowledge is the Context below.

ABSOLUTE RULES - YOU MUST FOLLOW THESE:
1. If the Context does NOT contain information to answer the question, you MUST respond with EXACTLY:
   "{REFUSAL_STRING}"
2. This includes ALL questions about topics not covered in the PDFs
3. Do NOT use ANY outside knowledge or common sense
4. Do NOT make up ANY information
5. If you are unsure, ALWAYS choose the refusal message

Context:
{context}"""},
        {"role": "user", "content": question}
    ]

    prompt = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)

    inputs = tokenizer(prompt, return_tensors="pt", truncation=True, max_length=2048)
    if torch.cuda.is_available():
        inputs = {k: v.cuda() for k, v in inputs.items()}

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=150,
            temperature=0.1,  # Low temperature for factual responses
            do_sample=True,
            top_p=0.9,
            num_beams=1,
            pad_token_id=tokenizer.pad_token_id,
            eos_token_id=tokenizer.eos_token_id
        )

    response = tokenizer.decode(outputs[0][inputs['input_ids'].shape[1]:], skip_special_tokens=True).strip()

    # Safety check: if response is short and contains forbidden topic, refuse
    if contains_forbidden and len(response.split()) < 15 and REFUSAL_STRING not in response:
        # Check if response actually contains info from context
        if not any(sent in context for sent in response.split('.') if len(sent) > 20):
            return REFUSAL_STRING

    return response

def calculate_precision_at_k(question, k=5):
    """Calculate precision@k for retrieved chunks"""
    instruction = "Represent this sentence for searching relevant passages: "
    query_text = instruction + question
    q_emb = embedder.encode([query_text], normalize_embeddings=True, convert_to_numpy=True)
    distances, indices = faiss_index.search(q_emb, k)

    actual_chunks = [pdf_chunks[i] for i in indices[0]]

    question_emb = semantic_model.encode([question])
    chunk_embs = semantic_model.encode(actual_chunks)
    similarities = cosine_similarity(question_emb, chunk_embs)[0]

    relevant_count = sum(1 for sim in similarities if sim > 0.60)
    return relevant_count / k if k > 0 else 0

def calculate_context_relevancy(question, context):
    """Calculate how relevant the context is to the question"""
    question_emb = semantic_model.encode([question])
    context_emb = semantic_model.encode([context])
    similarity = cosine_similarity(question_emb, context_emb)[0][0]
    return float(similarity)

def calculate_faithfulness(answer, context):
    """Calculate if answer is faithful to context"""
    if REFUSAL_STRING in answer:
        return 0.0

    answer_sentences = [s.strip() for s in re.split(r'[.!?]+', answer) if len(s.strip()) > 10]
    context_sentences = [s.strip() for s in re.split(r'[.!?]+', context) if len(s.strip()) > 10]

    if not answer_sentences or not context_sentences:
        return 0.0

    ans_embs = semantic_model.encode(answer_sentences)
    ctx_embs = semantic_model.encode(context_sentences)

    sim_matrix = cosine_similarity(ans_embs, ctx_embs)

    supported_count = 0
    for i in range(len(answer_sentences)):
        if max(sim_matrix[i]) > 0.60:
            supported_count += 1

    return supported_count / len(answer_sentences)

def calculate_answer_relevancy(question, answer):
    """Calculate if answer is relevant to question"""
    if REFUSAL_STRING in answer:
        return 0.0

    question_emb = semantic_model.encode([question])
    answer_emb = semantic_model.encode([answer])
    similarity = cosine_similarity(question_emb, answer_emb)[0][0]
    return float(similarity)

def calculate_groundedness(answer, context):
    """Calculate if answer is grounded in context"""
    if REFUSAL_STRING in answer:
        return 0.0

    answer_emb = semantic_model.encode([answer])
    context_emb = semantic_model.encode([context])
    similarity = cosine_similarity(answer_emb, context_emb)[0][0]
    return float(similarity)

print("All evaluation functions defined successfully!")

# CELL 14: Run Comprehensive Evaluation with Qwen
print("Running comprehensive evaluation on validation set...")

# Initialize metrics storage
all_metrics = {
    'precision@3': [],
    'context_relevancy': [],
    'faithfulness': [],
    'groundedness': [],
    'answer_relevancy': [],
    'rouge_f1': [],
    'bleu': []
}

detailed_results = []

# Initialize ROUGE scorer
scorer = rouge_scorer.RougeScorer(['rouge1', 'rouge2', 'rougeL'], use_stemmer=True)

# Evaluate on validation set
for i, pair in enumerate(val_qa[:min(20, len(val_qa))]):  # Test on up to 20
    q = pair['question']
    ref = pair['answer']
    context = pair['context']

    try:
        # Get retrieved context
        retrieved_context = retrieve_top_k_chunks(q, k=5)

        # Generate answer using Qwen
        pred = ask_qwen(model, tokenizer, q, retrieved_context)

        # Calculate metrics
        precision_k = calculate_precision_at_k(q, k=3)
        context_rel = calculate_context_relevancy(q, retrieved_context)
        faithfulness = calculate_faithfulness(pred, retrieved_context)
        groundedness = calculate_groundedness(pred, retrieved_context)
        answer_rel = calculate_answer_relevancy(q, pred)

        # Traditional metrics
        rouge_scores = scorer.score(ref, pred)
        rouge_f1 = (rouge_scores['rouge1'].fmeasure +
                    rouge_scores['rouge2'].fmeasure +
                    rouge_scores['rougeL'].fmeasure) / 3

        # BLEU score
        try:
            ref_tokens = word_tokenize(ref.lower())
            pred_tokens = word_tokenize(pred.lower())
            smoothie = SmoothingFunction().method4
            bleu = sentence_bleu([ref_tokens], pred_tokens, smoothing_function=smoothie)
        except:
            bleu = 0

        # Store metrics
        metrics = {
            'precision@3': precision_k,
            'context_relevancy': context_rel,
            'faithfulness': faithfulness,
            'groundedness': groundedness,
            'answer_relevancy': answer_rel,
            'rouge_f1': rouge_f1,
            'bleu': bleu
        }

        for key in all_metrics:
            all_metrics[key].append(metrics[key])

        detailed_results.append({
            'question': q[:100] + '...' if len(q) > 100 else q,
            'reference': ref[:150] + '...' if len(ref) > 150 else ref,
            'prediction': pred[:150] + '...' if len(pred) > 150 else pred,
            **{k: round(v, 4) for k, v in metrics.items()}
        })

        print(f"\nExample {i+1}:")
        print(f"Q: {q[:80]}...")
        print(f"A: {pred[:100]}...")
        print(f"Precision@3: {metrics['precision@3']:.3f}")
        print(f"Faithfulness: {metrics['faithfulness']:.3f}")

    except Exception as e:
        print(f"Error evaluating example {i}: {e}")
        continue

# Calculate average metrics
avg_metrics = {k: np.mean(v) if v else 0 for k, v in all_metrics.items()}

print("\n" + "="*60)
print("QWEN EVALUATION RESULTS")
print("="*60)
print("\nAverage Metrics:")
print("-" * 40)
for metric, value in avg_metrics.items():
    print(f"{metric:20s}: {value:.4f}")

# Save results
results_df = pd.DataFrame(detailed_results)
results_df.to_csv(f"{results_dir}/evaluation_results.csv", index=False)
print(f"\nDetailed results saved to {results_dir}/evaluation_results.csv")

# CELL 15: CREATE INTERACTIVE CHAT WIDGET WITH EVALUATION METRICS
import ipywidgets as widgets
from IPython.display import display, clear_output, HTML
import pandas as pd
from datetime import datetime
import numpy as np

print("Setting up Interactive Chat Interface...")

# Create widgets
question_input = widgets.Text(
    placeholder="Ask a question about autism...",
    description="You:",
    layout=widgets.Layout(width="70%"),
    style={'description_width': 'initial'}
)

send_button = widgets.Button(
    description="Send",
    button_style="primary",
    layout=widgets.Layout(width="10%")
)

clear_button = widgets.Button(
    description="Clear History",
    button_style="warning",
    layout=widgets.Layout(width="15%")
)

show_metrics_checkbox = widgets.Checkbox(
    value=True,
    description="Show evaluation metrics",
    style={'description_width': 'initial'},
    layout=widgets.Layout(width="30%")
)

# Create output areas
output_area = widgets.Output()
eval_summary_area = widgets.Output()

# Store chat history with metrics
chat_history = []

# Display widgets
display(widgets.HBox([question_input, send_button, clear_button]))
display(show_metrics_checkbox)
display(output_area)
display(eval_summary_area)

def create_metrics_table(metrics_dict):
    """Create a formatted HTML table of metrics"""
    html = """
    <table style="width:100%; border-collapse: collapse; margin: 10px 0; font-family: Arial, sans-serif;">
        <tr style="background-color: #f2f2f2;">
            <th style="padding: 8px; text-align: left; border: 1px solid #ddd;">Metric</th>
            <th style="padding: 8px; text-align: left; border: 1px solid #ddd;">Score</th>
        </tr>
    """
    for metric, score in metrics_dict.items():
        # Determine color based on score
        color = '#4ECDC4' if score >= 0.7 else '#FFD166' if score >= 0.4 else '#FF6B6B'

        html += f"""
        <tr>
            <td style="padding: 8px; border: 1px solid #ddd;">{metric.replace('_', ' ').title()}</td>
            <td style="padding: 8px; border: 1px solid #ddd; background-color: {color}20; font-weight: bold;">
                {score:.3f}
            </td>
        </tr>
        """
    html += "</table>"
    return HTML(html)

def handle_question(_):
    """Process the user's question, run Qwen, and evaluate"""
    question = question_input.value.strip()
    if not question:
        return

    # Clear input
    question_input.value = ""

    with output_area:
        clear_output(wait=True)
        print(f"\n{'='*60}")
        print(f"Q: {question}")
        print(f"{'='*60}")
        print("\n🤔 Searching PDFs and generating answer...")

        # 1. Retrieve Context
        context = retrieve_top_k_chunks(question, k=5)

        # 2. Generate Answer
        answer = ask_qwen(model, tokenizer, question, context)

        # Display Answer
        print(f"\nA: {answer}\n")
        print(f"{'-'*60}")

    # Evaluate if checkbox is ticked
    if show_metrics_checkbox.value:
        with eval_summary_area:
            clear_output(wait=True)
            print("\n📊 EVALUATING RESPONSE...")

            # Calculate all metrics
            metrics = {
                'precision@5': calculate_precision_at_k(question, k=5),
                'context_relevancy': calculate_context_relevancy(question, context),
                'faithfulness': calculate_faithfulness(answer, context),
                'answer_relevancy': calculate_answer_relevancy(question, answer),
                'groundedness': calculate_groundedness(answer, context)
            }

            # Log to history
            chat_history.append({
                'timestamp': datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
                'question': question,
                'answer': answer,
                'context': context[:200] + '...' if len(context) > 200 else context,
                **metrics
            })

            clear_output(wait=True)
            print(f"\n📊 EVALUATION METRICS")
            print(f"{'='*40}")
            display(create_metrics_table(metrics))

            # Add overall confidence score
            avg_score = sum(metrics.values()) / len(metrics)
            color = '#4ECDC4' if avg_score > 0.7 else '#FFD166' if avg_score > 0.4 else '#FF6B6B'
            display(HTML(f"""
            <div style="margin: 10px 0; padding: 10px; background-color: {color}20; border-left: 4px solid {color};">
                <strong>Overall Quality Score:</strong> {avg_score:.3f}
            </div>
            """))

    else:
        with eval_summary_area:
            clear_output(wait=True)

def clear_history(_):
    """Clear chat history"""
    global chat_history
    chat_history = []
    with eval_summary_area:
        clear_output(wait=True)
        print("✅ Chat history cleared!")
    with output_area:
        clear_output(wait=True)
        print("Chat history cleared. Start a new conversation!")

# Connect UI actions
question_input.on_submit(handle_question)
send_button.on_click(handle_question)
clear_button.on_click(clear_history)

print("✅ Chat interface with evaluation metrics ready! Type a question above.")
print(f"   - Total QA pairs in training: {len(train_qa)}")
print(f"   - Total chunks in knowledge base: {len(pdf_chunks)}")

# CELL 15.2 - Dual Visualization (Radar + Bar) for Each Question
import matplotlib.pyplot as plt
import numpy as np

def display_full_analysis():
    if 'chat_history' not in globals() or not chat_history:
        print("No chat history found. Please run the Chat Widget in Cell 15 first.")
        return

    # Define the metrics to display
    metrics_keys = ['precision@5', 'context_relevancy', 'faithfulness', 'answer_relevancy', 'groundedness']
    labels = [k.replace('_', '\n').title() for k in metrics_keys]

    print(f"📊 Generating Dual Analysis for {len(chat_history)} questions...\n")

    for i, entry in enumerate(chat_history, 1):
        # Extract values for this specific question
        values = [entry.get(k, 0) for k in metrics_keys]

        # Create a figure with two subplots (1 row, 2 columns)
        fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 6), gridspec_kw={'width_ratios': [1, 1.2]})

        # --- 1. RADAR CHART (Left) ---
        angles = np.linspace(0, 2 * np.pi, len(metrics_keys), endpoint=False).tolist()
        radar_values = values + values[:1]
        radar_angles = angles + angles[:1]

        ax1 = plt.subplot(1, 2, 1, polar=True)
        ax1.fill(radar_angles, radar_values, color='teal', alpha=0.25)
        ax1.plot(radar_angles, radar_values, color='teal', linewidth=2, marker='o')
        ax1.set_xticks(angles)
        ax1.set_xticklabels(labels, size=9)
        ax1.set_ylim(0, 1)
        ax1.set_title(f"Metric Balance (Q{i})", pad=20)

        # --- 2. BAR GRAPH (Right) ---
        colors = ['#4e79a7', '#f28e2b', '#e15759', '#76b7b2', '#59a14f']
        bars = ax2.bar(labels, values, color=colors, alpha=0.8)
        ax2.set_ylim(0, 1.1) # Extra space for text labels
        ax2.set_ylabel('Score (0.0 - 1.0)')
        ax2.set_title(f"Score Breakdown (Q{i})")
        ax2.grid(axis='y', linestyle='--', alpha=0.6)

        # Add text labels on top of bars
        for bar in bars:
            height = bar.get_height()
            ax2.text(bar.get_x() + bar.get_width()/2., height + 0.02,
                    f'{height:.2f}', ha='center', va='bottom', fontweight='bold')

        plt.suptitle(f"QUESTION {i}: {entry['question'][:75]}...", fontsize=14, fontweight='bold', y=1.05)
        plt.tight_layout()
        plt.show()

        print(f"Full Question: {entry['question']}")
        print("-" * 100)

# Run the visualization
display_full_analysis()

# CELL 15.3 - Save Dual Visualizations to Google Drive
import matplotlib.pyplot as plt
import numpy as np
import os
from google.colab import drive

def save_and_display_analysis():
    # 1. Mount Google Drive and set up the folder
    drive.mount('/content/drive', force_remount=True)
    drive_save_path = '/content/drive/MyDrive/Autism_Chatbot_Evaluation'
    os.makedirs(drive_save_path, exist_ok=True)

    if 'chat_history' not in globals() or not chat_history:
        print("No chat history found. Please run the Chat Widget in Cell 15 first.")
        return

    metrics_keys = ['precision@5', 'context_relevancy', 'faithfulness', 'answer_relevancy', 'groundedness']
    labels = [k.replace('_', '\n').title() for k in metrics_keys]

    print(f"📊 Processing {len(chat_history)} questions. Graphs will be saved to: {drive_save_path}\n")

    for i, entry in enumerate(chat_history, 1):
        values = [entry.get(k, 0) for k in metrics_keys]

        # Create a figure with two subplots
        fig = plt.figure(figsize=(16, 7))

        # --- 1. RADAR CHART (Left) ---
        angles = np.linspace(0, 2 * np.pi, len(metrics_keys), endpoint=False).tolist()
        radar_values = values + values[:1]
        radar_angles = angles + angles[:1]

        ax1 = fig.add_subplot(121, polar=True)
        ax1.fill(radar_angles, radar_values, color='#008080', alpha=0.3)
        ax1.plot(radar_angles, radar_values, color='#008080', linewidth=2.5, marker='o')
        ax1.set_xticks(angles)
        ax1.set_xticklabels(labels, size=10, fontweight='bold')
        ax1.set_ylim(0, 1)
        ax1.set_title(f"Metric Balance (Q{i})", pad=30, fontsize=14)

        # --- 2. BAR GRAPH (Right) ---
        ax2 = fig.add_subplot(122)
        colors = ['#4e79a7', '#f28e2b', '#e15759', '#76b7b2', '#59a14f']
        bars = ax2.bar(labels, values, color=colors, alpha=0.85, edgecolor='black', linewidth=1)
        ax2.set_ylim(0, 1.1)
        ax2.set_ylabel('Score (0.0 - 1.0)', fontsize=12)
        ax2.set_title(f"Detailed Score Breakdown (Q{i})", fontsize=14)
        ax2.grid(axis='y', linestyle='--', alpha=0.5)

        # Add data labels on top of bars
        for bar in bars:
            height = bar.get_height()
            ax2.text(bar.get_x() + bar.get_width()/2., height + 0.02,
                    f'{height:.2f}', ha='center', va='bottom', fontsize=11, fontweight='bold')

        # Overall Title
        plt.suptitle(f"QUESTION {i} ANALYSIS\nQ: {entry['question'][:80]}...",
                     fontsize=16, fontweight='bold', y=1.02)

        # Save to Drive
        filename = f"evaluation_q{i}_{entry['timestamp'].replace(':', '-').replace(' ', '_')}.png"
        save_file_path = os.path.join(drive_save_path, filename)
        plt.savefig(save_file_path, bbox_inches='tight', dpi=150)

        # Display in Notebook
        plt.tight_layout()
        plt.show()

        print(f"✅ Saved to Drive: {filename}")
        print("-" * 100)

# Execute the process
save_and_display_analysis()

# CELL 16: VIEW CHAT HISTORY & AVERAGE SESSION METRICS
def show_chat_history():
    """Display chat history with accumulated metrics"""
    if not chat_history:
        print("No questions asked yet.")
        return

    history_df = pd.DataFrame(chat_history)

    print("📋 CHAT HISTORY SUMMARY")
    print("="*60)

    # Display each entry
    for i, entry in enumerate(chat_history, 1):
        # Color indicator based on Faithfulness
        color = '🟢' if entry['faithfulness'] > 0.7 else '🟡' if entry['faithfulness'] > 0.4 else '🔴'

        print(f"\n{i}. [{entry['timestamp']}] {color}")
        print(f"   Q: {entry['question']}")
        print(f"   A: {entry['answer'][:120]}...")
        print(f"   Metrics: Precision@5={entry['precision@5']:.3f}, "
              f"Faithfulness={entry['faithfulness']:.3f}, "
              f"Answer Rel={entry['answer_relevancy']:.3f}")

    # Display session averages
    print("\n" + "="*60)
    print("SESSION AVERAGES:")
    avg_metrics = history_df[['precision@5', 'context_relevancy', 'faithfulness', 'answer_relevancy', 'groundedness']].mean()

    for metric, value in avg_metrics.items():
        print(f"{metric:20s}: {value:.3f}")

# Execute to show history
show_chat_history()

# CELL 17: Test the Model with Custom Questions & Generate Graphs
import matplotlib.pyplot as plt
import numpy as np
import os

print("Testing the model with custom questions...")

test_questions = [
    # Answerable Questions
    "What is autism?",
    "What are the main symptoms of autism?",
    "How is autism diagnosed?",
    "What treatments are available for autism?",
    "What causes autism?",
    "How common is autism?",
    "What are early signs of autism in children?",
    "Who was Bernard Rimland?",
    "What is the prevalence of sleep problems in ASD?",
    "What is Asperger's syndrome?",
    "What did Leo Kanner discover?",
    "What is the GFCF diet?",

    # Unanswerable Questions
    "How to make a burger?",
    "What is the capital of France?",
    "Who won the Super Bowl in 2023?",
    "What is the recipe for chocolate cake?",
    "How to change a car tire?",
    "What is the population of Tokyo?",
    "Who invented the telephone?",
    "What is the weather forecast for tomorrow?",
    "How to knit a scarf?",
    "What is the stock price of Apple?",
    "How to bake bread?",
    "What's the best way to fix a leaky faucet?"
]

# Enhanced refusal patterns
PROCEDURAL_PATTERNS = [
    r'how to (make|bake|cook|prepare|create|build|fix|repair|change|replace|install|knit|sew)',
    r'recipe for',
    r'instructions? (for|on)',
    r'steps? to',
    r'guide (to|for)',
    r'tutorial',
]

GENERAL_KNOWLEDGE_PATTERNS = [
    r'capital of',
    r'president of',
    r'prime minister',
    r'population of',
    r'invented the',
    r'discovered',
    r'weather',
    r'forecast',
    r'temperature',
    r'stock price',
    r'share price',
    r'super bowl',
    r'world cup',
    r'olympics',
    r'championship',
    r'election',
]

def should_force_refusal(question, context, precision):
    """Enhanced refusal detection"""
    question_lower = question.lower()

    # Check precision - if retrieval failed, be more suspicious
    if precision < 0.3:
        # Check for procedural questions
        for pattern in PROCEDURAL_PATTERNS:
            if re.search(pattern, question_lower):
                return True

        # Check for general knowledge
        for pattern in GENERAL_KNOWLEDGE_PATTERNS:
            if pattern in question_lower or re.search(pattern, question_lower):
                return True

    # Check context quality
    if len(context.strip()) < 150 or "Source:" not in context:
        # Suspicious if context is too short or missing source marker
        if any(keyword in question_lower for keyword in ['how', 'what is', 'who', 'when', 'where']):
            # But only refuse if it's clearly not autism-related
            autism_keywords = ['autism', 'asd', 'asperger', 'spectrum', 'disorder',
                              'developmental', 'behavior', 'child', 'treatment',
                              'therapy', 'symptom', 'diagnosis', 'kanner', 'rimland']
            if not any(keyword in question_lower for keyword in autism_keywords):
                return True

    return False

precisions = []
relevancies = []
refusal_correct = []
questions_labels = [f"Q{i+1}" for i in range(len(test_questions))]

for i, question in enumerate(test_questions):
    print(f"\n{'='*50}")
    print(f"Question {i+1}: {question}")
    print(f"{'='*50}")

    # Get context
    context = retrieve_top_k_chunks(question, k=3)
    print(f"\nRetrieved Context (preview): {context[:200]}...")

    # Calculate precision first
    precision = calculate_precision_at_k(question, k=3)

    # Check if this should be refused
    should_refuse = should_force_refusal(question, context, precision)

    # Generate answer
    if should_refuse:
        answer = REFUSAL_STRING
        print(f"\n🔒 FORCED REFUSAL (out-of-domain question)")
    else:
        answer = ask_qwen(model, tokenizer, question, context)

    print(f"\nAnswer: {answer}")

    # Calculate metrics
    relevancy = calculate_answer_relevancy(question, answer)

    precisions.append(precision)
    relevancies.append(relevancy)

    # Track if refusal was correct (for out-of-domain questions)
    is_out_of_domain = i >= 12  # Questions after index 12 are out-of-domain
    if is_out_of_domain:
        was_refused = (REFUSAL_STRING in answer)
        refusal_correct.append(was_refused)
        refusal_status = "✅ CORRECT REFUSAL" if was_refused else "❌ SHOULD HAVE REFUSED"
    else:
        refusal_status = "IN-DOMAIN"

    print(f"\nMetrics:")
    print(f"- Precision@3: {precision:.3f}")
    print(f"- Answer Relevancy: {relevancy:.3f}")
    print(f"- Status: {refusal_status}")

# Calculate refusal accuracy
if refusal_correct:
    refusal_accuracy = sum(refusal_correct) / len(refusal_correct) * 100
    print(f"\n{'='*50}")
    print(f"REFUSAL ACCURACY: {refusal_accuracy:.1f}% ({sum(refusal_correct)}/{len(refusal_correct)} correct)")
    if refusal_accuracy < 100:
        print("⚠️  Some out-of-domain questions were not properly refused.")

# --- Generate Visualization ---
print(f"\n📊 Generating metrics graph for custom questions...")
plt.figure(figsize=(14, 6))

# Create color-coded bars based on domain
colors_precision = []
colors_relevancy = []
for i in range(len(test_questions)):
    if i < 12:  # In-domain
        colors_precision.append('#4e79a7')  # Blue
        colors_relevancy.append('#f28e2b')  # Orange
    else:  # Out-of-domain
        colors_precision.append('#e15759' if precisions[i] > 0.3 else '#4e79a7')  # Red if false positive
        colors_relevancy.append('#e15759' if relevancies[i] > 0.3 else '#f28e2b')  # Red if false positive

x = np.arange(len(questions_labels))
width = 0.35

bars1 = plt.bar(x - width/2, precisions, width, label='Precision@3', color=colors_precision)
bars2 = plt.bar(x + width/2, relevancies, width, label='Answer Relevancy', color=colors_relevancy)

# Add a vertical line separating in-domain from out-of-domain
plt.axvline(x=11.5, color='red', linestyle='--', alpha=0.5, label='Domain Boundary')

plt.ylabel('Score (0.0 - 1.0)')
plt.title('Evaluation Metrics for Custom Test Questions\n(Left: In-Domain | Right: Out-of-Domain)')
plt.xticks(x, questions_labels, rotation=45)
plt.ylim(0, 1.1)
plt.legend()
plt.grid(axis='y', linestyle='--', alpha=0.6)

# Add value labels on bars
for bars in [bars1, bars2]:
    for bar in bars:
        height = bar.get_height()
        if height > 0.01:
            plt.text(bar.get_x() + bar.get_width()/2., height + 0.02,
                    f'{height:.2f}', ha='center', va='bottom', fontsize=8, rotation=45)

plt.tight_layout()

# Save graph locally
custom_eval_path = f"{plots_dir}/custom_questions_evaluation.png"
plt.savefig(custom_eval_path, bbox_inches='tight', dpi=150)
plt.show()
print(f"✅ Local custom evaluation graph saved to {custom_eval_path}")

# Print summary statistics
print(f"\n{'='*50}")
print("SUMMARY STATISTICS")
print(f"{'='*50}")
in_domain_precision = np.mean(precisions[:12]) if precisions[:12] else 0
in_domain_relevancy = np.mean(relevancies[:12]) if relevancies[:12] else 0
out_domain_precision = np.mean(precisions[12:]) if precisions[12:] else 0
out_domain_relevancy = np.mean(relevancies[12:]) if relevancies[12:] else 0

print(f"In-Domain Questions (1-12):")
print(f"  - Avg Precision@3: {in_domain_precision:.3f}")
print(f"  - Avg Answer Relevancy: {in_domain_relevancy:.3f}")
print(f"\nOut-of-Domain Questions (13-24):")
print(f"  - Avg Precision@3: {out_domain_precision:.3f}")
print(f"  - Avg Answer Relevancy: {out_domain_relevancy:.3f}")
if 'refusal_accuracy' in locals():
    print(f"  - Refusal Accuracy: {refusal_accuracy:.1f}%")

# CELL 17.1: Save Cell 17 Visualizations to Google Drive
from google.colab import drive
import shutil
import os

print("Mounting Google Drive...")
drive.mount('/content/drive')

# Point to Google Drive directory
drive_results_dir = '/content/drive/MyDrive/Qwen_RAG_Results'
os.makedirs(drive_results_dir, exist_ok=True)

# Ensure it only refers to Cell 17's Data
local_eval_path = f"{plots_dir}/custom_questions_evaluation.png"
drive_eval_path = f"{drive_results_dir}/custom_questions_evaluation.png"

if os.path.exists(local_eval_path):
    # Submit only the graph generated in Cell 17
    shutil.copy2(local_eval_path, drive_eval_path)
    print(f"✅ Cell 17 Custom evaluation graph saved to Google Drive: {drive_eval_path}")
else:
    print("❌ Custom evaluation graph not found. Please make sure Cell 17 was executed successfully.")